apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
        - args:
            - bin/spark-class
            - org.apache.spark.deploy.master.Master
            - -h
            - master
          env:
            - name: MASTER
              value: spark://master:7077
            - name: SPARK_CONF_DIR
              value: /conf
            - name: SPARK_DIVER_CORES
              value: "1"
            - name: SPARK_DRIVER_MEMORY
              value: 1g
            - name: SPARK_PUBLIC_DNS
              value: localhost
          image: renien/spark-stand-alone
          name: spark-master
          ports:
            - containerPort: 6066
            - containerPort: 7077
            - containerPort: 8080
            - containerPort: 7001
            - containerPort: 7002
            - containerPort: 7003
            - containerPort: 7004
            - containerPort: 7005
          resources: {}
          volumeMounts:
            - mountPath: /conf
              name: spark-master-claim0
            - mountPath: /tmp/data
              name: spark-master-claim1
      hostname: master
      restartPolicy: Always
      volumes:
        - name: spark-master-claim0
          persistentVolumeClaim:
            claimName: spark-master-claim0
        - name: spark-master-claim1
          persistentVolumeClaim:
            claimName: spark-master-claim1
status: {}
